### ISSUE TITLE
OpenZaak 2.0 new website design

### ISSUE THREAD

**Issue by felixfaassen** [open-zaak/open-zaak-website#37]
The current website is a barebones version which is only in English and not in Dutch. Also the website lacks basic context and background information which is up-to-date.

- New website with structure like signalen.org
- Website with information on history project, background, purpose
- Info on how to use openzaak
- Info on how to reach the community
- Roadmap

**Tasks:**

- [x] Adapt signalen.org towards OpenZaak
- [x] Create new copy for OpenZaak in dutch
- [x] Translate copy to English
- [x] Implement changes into code NL
- [x] Implement changes into code EN
- [x] Include community logo's on website
- [x] refine contact pages
- [ ] gather community feedback
- [x] Configure CI/CD and hosting
- [x] Test CI/CD
- [x] Test deployment to Github pages using Github actions

**Comment by felixfaassen** [comment]
Tasks:

- [x] Adapt signalen.org towards OpenZaak
- [x] Create new copy for OpenZaak in dutch
- [ ] Translate copy to English
- [ ] Include logo's on website
- [ ] refine contact pages
